spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/m2ibank1?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
server.port=8090
jwt.secret=YDzwxjqQNDlEKL+3yhG6dc6Rx4gbAFsQHUbvs01xK8hAP5qISsIah7e2y1pTgBt2+xD4V+rDp2Yz2hzgPyeZWQ==
